### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by yupferris** [tomaka/cpal#104]
Just wanted to make a cover-all issue for this. Known dependencies include:

https://github.com/tomaka/cpal/issues/52

Latest [coreaudio-rs](https://github.com/RustAudio/coreaudio-rs) (>=0.5.0) should have no problems supporting this at this point, but we need to put in the hours to actually fix everything up again :)

**Comment by emoon** [comment]
cc @emoon

**Comment by yupferris** [comment]
I literally just tried to build rodio on OS X forgetting that it depends on this crate and that we still haven't fixed this yet :P

**Comment by mitchmindtree** [comment]
@yupferris If you want to try updating CPAL to the latest coreaudio-rs i'd be happy to offer any help if you need it or get stuck :+1:

**Comment by yupferris** [comment]
thanks :) I am interested in giving it a shot, but I won't be able to dig that deep until at least next week unfortunately.

**Comment by jansol** [comment]
For everyone interested: please take a look at PR #114

**Comment by yupferris** [comment]
cc @mitchmindtree

**Comment by yupferris** [comment]
It looks like this is solved now, is it not?

**Comment by HybridEidolon** [comment]
I think there is enough minimum support for macOS now in both the latest published version and master to close this, although there are other features that need work. Both examples work great in 10.12.

**Comment by emoon** [comment]
I have been using Rodio (that uses cpal) a bit on my Mac and it seems to work great!

**Comment by yupferris** [comment]
There's still https://github.com/tomaka/cpal/issues/148 which is certainly related but may be specific to rodio (see https://github.com/tomaka/rodio/issues/94). However since that's contained in its own open ticket(s) already, I think it's safe to close this.
