### ISSUE TITLE
Creating Voice with custom format could trigger panic

### ISSUE THREAD

**Issue by mvdnes** [tomaka/cpal#109]
When creating a new `Voice` in _alsa_, there are a lot of [lines](https://github.com/tomaka/cpal/blob/b20a76aab8a5574b1256683f8b3b0d5225030d9e/src/alsa/mod.rs#L231-L238) that use the `expect` function.
In one of my projects, rather than enumerating all formats I tried to guess the best format available by constructing one myself. Since `Voice::new` returns an option, I would expect that, given an invalid `Format`, I would recieve `Err(FormatNotSupported)` rather than a panic from which I cannot recover.

Shouldn't some of these use `try!` rather than `expect`?

**Comment by tomaka** [comment]
An error definitely should be returned in the format is wrong.
However some of the lines you linked use `expect` because if these function calls fail it always indicates that there's a bug either in cpal or in alsa.

A function call which can legitimately return an error should do so, but function calls that are never supposed to fail should just panic.

**Comment by mvdnes** [comment]
I have the following code. I wrote this to determine a high supported sample rate, and to check if `F32` is supported.
```rust
let mut wanted_samplerate = None;
let mut wanted_sampleformat = None;
for f in endpoint.get_supported_formats_list().unwrap() {
    match wanted_samplerate {
        None => wanted_samplerate = Some(f.samples_rate),
        Some(cpal::SamplesRate(r)) if r < f.samples_rate.0 && r < 192000 => wanted_samplerate = Some(f.samples_rate),
        _ => {}, 
    }   
    match wanted_sampleformat {
        None => wanted_sampleformat = Some(f.data_type),
        Some(cpal::SampleFormat::F32) => {}, 
        Some(_) if f.data_type == cpal::SampleFormat::F32 => wanted_sampleformat = Some(f.data_type),
        _ => {}, 
    }   
}

if wanted_samplerate.is_none() || wanted_sampleformat.is_none() {
    return None;
}   

let format = cpal::Format {
    channels: vec![cpal::ChannelPosition::FrontLeft, cpal::ChannelPosition::FrontRight],
    samples_rate: wanted_samplerate.unwrap(),
    data_type: wanted_sampleformat.unwrap(),
};  
```

But this gives me the following when passing to `Voice::new`:

```
format: Format { channels: [FrontLeft, FrontRight], samples_rate: SamplesRate(192000), data_type: F32 }
thread '<main>' panicked at 'hardware params could not be set: "Invalid argument"', ../src/libcore/result.rs:746
```

But switching to
```rust
let format = endpoint.get_supported_formats_list().unwrap().next().unwrap();
```
gives me
```
format: Format { channels: [FrontLeft], samples_rate: SamplesRate(5512), data_type: I16 }
```
which does work.

**Comment by mvdnes** [comment]
I have had some time to once look at this situation. It seems that my earlier assessment was wrong.

I am trying to make a
```rust
Format { channels: [FrontLeft, FrontRight], samples_rate: SamplesRate(192000), data_type: F32 }
```
on Linux (alsa).

The error that appears is
```
thread '<main>' panicked at 'hardware params could not be set: "Invalid argument"', ../src/libcore/result.rs:746
```

However, it seems that this exact format _is_ in the `get_supported_formats_list()`. So it may be that that returns results that are too permissive.

**Comment by mitchmindtree** [comment]
As of #286, an appropriate error should be returned that should allow the user to handle this case.

If anyone reading this is still running into a discrepancy between the `supported_input/output_formats` and what is accepted when building a stream on ALSA, feel free to open up a new issue specifically for this problem.
