### ISSUE TITLE
Hitting debug_assertion on windows

### ISSUE THREAD

**Issue by Bobo1239** [tomaka/cpal#126]
Running the beep example I get:
```
thread 'main' panicked at 'assertion failed: !buffer.is_null()', src\wasapi\voice.rs:388
```
[(relevant code)](https://github.com/tomaka/cpal/blob/master/src/wasapi/voice.rs#L387)
Sometimes it happens quite early after I start the program but there are also times where I have to wait 1-2 minutes.

**Comment by tomaka** [comment]
That's weird, as the documentation says this can't happen: https://msdn.microsoft.com/en-us/library/windows/desktop/dd368243(v=vs.85).aspx

It only says:

> In Windows 7, GetBuffer can return the AUDCLNT_E_BUFFER_ERROR error code for an audio client that uses the endpoint buffer in the exclusive mode. This error indicates that the data buffer was not retrieved because a data packet was not available (*ppData received NULL). 

But the endpoint is never in exclusive mode.

**Comment by tomaka** [comment]
And since cpal checks the return value of the function, that means the function succeeds.

Could you put something like `if buffer.is_null() { println!("{:?}", hresult}; }` to make sure the return code is normal?

**Comment by Bobo1239** [comment]
I also added a `println!` for `frames_available` as that appears to be the problem:
```
frames_available: 441
frames_available: 441
frames_available: 441
frames_available: 0
hresult: 0
thread 'main' panicked at 'assertion failed: !buffer.is_null()', src\wasapi\voice.rs:389
```

**Comment by tomaka** [comment]
Oh, good catch.

**Comment by tomaka** [comment]
The change should be trivial.
Just add something like: `if frames_available == 0 { return Poll::NotReady; }`

Could you please try if it works, and if so submit a PR?
