### ISSUE TITLE
beep example panics 'Failed to get default endpoint' on macOS release builds

### ISSUE THREAD

**Issue by HybridEidolon** [tomaka/cpal#137]
I look all through the implementation and couldn't figure out why `cpal::get_default_endpoint` would return `None` under release builds. The coreaudio backend _always_ returns `Some(Endpoint)`. I confirmed this with a bunch of printlns everywhere. The execution gets all the way down to `event_loop.run();` but `thread 'main' panicked at 'Failed to get default endpoint'` just before it?

This happens on stable and nightly.

**Comment by shockham** [comment]
This seems to be related to #148

**Comment by HybridEidolon** [comment]
Seems to be resolved in master at the moment (using rustc 1.21). Closing for now.
