### ISSUE TITLE
Running beep.rs example with ALSA only loads data to buffer once

### ISSUE THREAD

**Issue by TheVillageIdiot2** [tomaka/cpal#142]
No modifications were made to code. When I put println! statements in the stream.for_each closure, they only are called once. Issue persists with both version 0.4.0 and 0.4.1 of crate.

No panics or anything, and the program is properly blocking on the event_loop.run() call. Really not sure what could be going wrong. I can post more specific details of my system if that would help, but I'm fairly new to rust/audio stuff so not sure what would be relevant.

**Comment by nchashch** [comment]
I tried to debug this problem and I have found that `libc::poll` call in `EventLoop::run` method in src/alsa/mod.rs at L258 doesn't return (it seems it just runs in an infinite loop) after a few iterations (hence a short bit of sound plays at the begining).

Also on my machine `Buffer::finish` method (defined at L674 in src/alsa/mod.rs) is called only once or twice (so `alsa::snd_pcm_writei` is called only once or twice) after that `SamplesStream::schedule` is called (maybe something goes wrong there) and then `Buffer::finish` is never called again.

**Comment by jwestfall69** [comment]
Can you guys verify the above patch fixes the beep stall.  

I'm a little unsatisfied with the patch with where I'm calling alsa::snd_pcm_sw_params_set_avail_min(),.  Its inside the bits that are setting up buffer_len/period_len values, which seems like bad form.

**Comment by tomaka** [comment]
@jwestfall69 The style is not a problem for me.
