### ISSUE TITLE
Beep example distorts sine in the long run

### ISSUE THREAD

**Issue by Bendrien** [tomaka/cpal#157]
I ran the beep example on three different machines (linux, mac and windows) all slightly adding noisy tones on top of the sine. Why?

**Comment by gmorenz** [comment]
I'm pretty sure it's just floating point rounding errors in the data source.

**Comment by jansol** [comment]
It is indeed a result of the time parameter losing accuracy over time due to floating point precision issues. Changing it to f64 makes the problem take longer to manifest, but does not eliminate it. The solution would be to loop it over a single interval.
