### ISSUE TITLE
Example fails when using ALSA through PulseAudio

### ISSUE THREAD

**Issue by Bobo1239** [tomaka/cpal#173]
When ALSA is using PulseAudio, the reported maximum sample rate is garbage (4294967295) and the beep example fails with `sample rate could not be set: "Invalid argument"`. (See e.g. [here](https://w3.ual.es/~vruiz/Docencia/Apuntes/Multimedia/ALSA/index.html#x1-1700016) for the reported values) Setting the sample rate manually works flawlessly.

I'm not sure if this is really fixable or if the example should just use a common sample rate. This problem also makes rodio completely unusable on my system as it also always uses the maximum sample rate.

**Comment by 0e4ef622** [comment]
This also seems to happen when using ALSA plugins that convert sample rates.

**Comment by Bobo1239** [comment]
This is indeed fixed now as the example is using `device.default_output_format()` which defaults to a sane value.
