### ISSUE TITLE
[CoreAudio] Remove vec allocation per callback

### ISSUE THREAD

**Issue by HybridEidolon** [tomaka/cpal#181]
The render callback passed to the audio unit currently has to allocate a new Vec buffer every time it's called, because cpal currently only exposes a single interleaved buffer of samples, but the callback may receive multiple buffers, one per channel (non-interleaved). The vec buffer is resampled into the individual callback channel buffers, which is a potentially inefficient per-sample interleaved copy.

The Rust CoreAudio binding does not currently allow you to specify the necessary parts of the `AudioStreamBasicDescription` struct in `set_stream_format` which would make the callback receive a single interleaved buffer for the channels. An interleaved incoming buffer would be passed directly to the cpal callback with no pre or post processing required, but without the necessary Rusty interface, we need to go lower into the sys bindings.

In order to specify this without modifying coreaudio-rs upstream, you would need to create the `AudioStreamBasicDescription` struct directly and use `set_property` instead. This would open the door for directly supporting other stream formats as well.

I would assume that zero allocations, zero sample processing is a design goal for the library and any muxing or resampling would be deferred to user code, so this is probably a bug.

This is a prerequisite for #180 (at least, to make it efficient).

**Comment by tomaka** [comment]
> I would assume that zero allocations, zero sample processing is a design goal for the library and any muxing or resampling would be deferred to user code, so this is probably a bug.

Yes.
