### ISSUE TITLE
The `ChannelPosition` API should be optional

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/cpal#187]
CPAL Is the first low-level audio API that I've personally come across that requires specifying abstract "channel positions" for particular channels. It gets particularly annoying when you do not know or care about the channel positions, but just want to specify some number of channels.

As an example, I'm currently working on an audio installation with 100+ channels that are laid out throughout an exhibition space. The actual positions of the speakers have no correlation with any of the offered `ChannelPosition`s whatsoever, yet as a user I'm still required to fill a `Vec` with arbitrary positions.

I wonder if we could make the channel positioning API optional somehow? In most cases that I've personally come across I've just wanted to specify a number of channels, though admittedly I've mostly worked on pro-audio stuff where I know what device I'm working with and have manual control over the positioning of each channel.

I'd also be curious as to which backends actually use the `ChannelPosition` info, and if so, how do they use it? I don't believe the macOS backend currently uses this (not sure if it provides an API to do so), and I'm unsure about linux or windows.

**Comment by tomaka** [comment]
Yeah I've been wanting to remove them actually.

Windows more or less uses the channel positions, in the sense that it will return an error if the positions don't match what the hardware expects.

**Comment by mitchmindtree** [comment]
Closed via #198.
