### ISSUE TITLE
[Windows] Stream cannot be used twice

### ISSUE THREAD

**Issue by willstott101** [tomaka/cpal#266]
For long running daemon processes (such as `librespot`) sometimes it can be useful to completely release an audio sink and re-acquire it later when it's needed. Maybe due to sound server errors when running for too long, or just being able to restart the stream when the default device changes.

~~I've been having trouble being able to re-establish a Stream on the same device on windows. When using Rodio the stream never seems to be dropped (I'm not sure if that's a bug or a workaround for this bug).~~ Solved by #241!

I've created a small test case based on `examples/beep.rs` called [`examples/beep_twice.rs`](https://github.com/willstott101/cpal/blob/beep_twice/examples/beep_twice.rs).

This seems to work ~~as expected~~ with ALSA on Ubuntu 18.04 but on my Windows 10 machine the second use of the same stream yields no audio output.

**Comment by willstott101** [comment]
To clarify that example is meant to play a 1 second beep, stop for 1 second, and then play a beep for 1 second afterwards.

**Comment by willstott101** [comment]
Sorry, I'm conflating two issues here. The main issue was fixed in #241! The second much less important **but still-existing** issue is that a stream can be re-used on Linux but not on Windows.

FYI the beep_twice example does indeed beep twice on windows (but only with git master) with the addition of this line before starting the second stream: `let stream_id = event_loop.build_output_stream(&device, &format).unwrap();`

**Comment by ishitatsuyuki** [comment]
This isn't how things are supposed to work. Your example no longer beeps twice on Linux (tested on master), so I suppose that the ALSA backend is also working as intended now.

The opposite of `destroy` is `new`. `destroy` will entirely invalidate a stream ID. I'm not sure what you're trying to achieve, but what you want is probably `pause` then `play`.
