### ISSUE TITLE
SamplesRate struct

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/cpal#29]
@tomaka Just curious, do you have some plans for the `SamplesRate` struct? From what I can see it seems like it could just be a type alias instead of a struct? Just thought I'd check!

Also I think `SampleRate` (without the `s`) is the more stereotypical naming choice (or even `SampleHz` to be more precise).

**Comment by tomaka** [comment]
The only purpose of `SamplesRate` is to have stronger typing.

**Comment by mitchmindtree** [comment]
Perhaps then we should either:

1. do the same for both `ChannelsCount` and `BufferSize` or
2. type alias `SamplesRate` instead (like `ChannelsCount` currently is)

The `append_data` method signature seems a little inconsistent otherwise.

**Comment by yupferris** [comment]
> Also I think SampleRate (without the s) is the more stereotypical naming choice (or even SampleHz to be more precise).

I know it's bikeshedding a bit, but +1 to this; it's typically called `SampleRate` and I must admit I got a bit irked inside reading it as it is now :)

**Comment by mitchmindtree** [comment]
Closing this following #199.
