### ISSUE TITLE
Unique naming to distinguish between traits and platform types?

### ISSUE THREAD

**Issue by mitchmindtree** [tomaka/cpal#294]
I'm currently having a go at updating come downstream code to the latest `Host` API changes and it has made the shared names between the traits and the platform hosts a little frustrating.

Specifically, the `cpal::{Host, Device, EventLoop, StreamId}` traits and the `cpal::platform::{Host, Device, EventLoop, StreamId}` types are often needed in the same module, which means either only importing the traits and using the types via the `cpal::platform::` namespace or importing both but importing either the platform types or the traits as some other name.

Also, seeing as the traits are in the crate root, it produces some confusing errors when updating code to the new API, as previously e.g. `cpal::EventLoop` would refer to a concrete type, whereas now it refers to a trait.

## Potential Solution

One solution that might make transitioning easier could be to move the traits into their own module (perhaps a `traits` module) and re-export the dynamically dispatched platform types from the crate root. This way, there should be a lot less breakage in existing user code, as the root will still contain all the default concrete types for `EventLoop`, `Device` and `StreamId`, and although their methods won't be immediately available the compiler should suggest importing the necessary traits.

This solution would require renaming the `Host`, `Device`, `EventLoop` and `StreamId` traits to something friendlier if we want to avoid naming import collisions with the concrete types. The first idea that comes to mind is `HostTrait`, `DeviceTrait`, etc, but I'm open to suggestions!

Another benefit of moving all traits into their own module would be that users could import them all at once `use cpal::traits::*;` without polluting the namespace with other items.

cc @ishitatsuyuki would be great to get your thoughts on this!

**Comment by ishitatsuyuki** [comment]
My current stance on naming is that `FooTrait` has unneeded verbosity while `Host` should be named `BarHost` because it avoids ambiguity (per https://github.com/tomaka/cpal/pull/289/files#r297052432).

I think we could name the macro-generated ones to something like `DynamicHost`, but the drawback is that `DynamicHost` has more use cases than `Host(Trait)` but the former would be longer to type with this design.

**Comment by mitchmindtree** [comment]
> while `Host` should be named `BarHost` because it avoids ambiguity (per https://github.com/tomaka/cpal/pull/289/files#r297052432).

I addressed this in [this commit](https://github.com/tomaka/cpal/commit/51eba20c449a8da7247abab2f485a356790e9e5c#diff-d4a10bd4f65585b8279ea317cc75c984R451) soon after your comment.

> I think we could name the macro-generated ones to something like `DynamicHost`, but the drawback is that `DynamicHost` has more use cases than Host(Trait) but the former would be longer to type with this design.

> My current stance on naming is that FooTrait has unneeded verbosity

Yes I initially considered `DynamicHost` or `DynHost` too, but then considered that maybe the verbosity of the `Trait` postfix on the traits is worth allowing to use `Host` for the more common use case? This is the predicament that lead me to raise this issue :stuck_out_tongue:
