### ISSUE TITLE
Allow customisation of the Voice output format

### ISSUE THREAD

**Issue by Aatch** [tomaka/cpal#46]
As far as I can tell, all three output backends support multiple output formats. However each one is currently only configured for a single output format. Since different audio sources will have different formats, this means any source not in the hardcoded format for the voice has to be converted. This can actually mean a loss of fidelity in some cases, since it's possible to get formats that have 32-bit integer samples and even 64-bit float samples.

If the backend doesn't support a format, the conversion can be done then. I'd rather have the backend do the conversion if the hardware doesn't support a format than be forced to lose fidelity because the format is hard-coded.

Related to #30

**Comment by tomaka** [comment]
> As far as I can tell, all three output backends support multiple output formats.

Don't you have to recreate a channel if you want to change the format?

**Comment by Aatch** [comment]
I'm not sure I understand what you mean. What I want is a way to say that a given Voice's sample format is an unsigned byte per channel, or a signed 32-bit integer or similar. Rather than being fixed to a single specific type for each backend.

**Comment by tomaka** [comment]
Ah, you mean at initialization.
Some sound files can have frames with multiple different formats, and I thought you were talking about this.

**Comment by tomaka** [comment]
This is now the case with the new design.
