### ISSUE TITLE
music example fails on OSX due to AudioUnit frame size

### ISSUE THREAD

**Issue by HybridEidolon** [tomaka/cpal#52]
```
thread '<unnamed>' panicked at 'The number of input frames given differs from the number requested by the AudioUnit: 64 and 512 respectively', [src/coreaudio/mod.rs:103](https://github.com/tomaka/cpal/blob/6ffdcd5343fffabffd7472e60962a72405f52f93/src/coreaudio/mod.rs#L103)
```

Running Yosemite 10.10.4.

Similarly, the `beep` example sigsegvs during execution, only playing the beep for a very short period of time.

**Comment by bvssvni** [comment]
I got a machine to test this, if I get some pointers then perhaps I could fix it.

**Comment by mitchmindtree** [comment]
@bvssvni the issue is probably within [coreaudio-rs](https://github.com/RustAudio/coreaudio-rs) - I don't think we handle different buffer sizes properly, though I think @yupferris is working on it? There's an issue [here](https://github.com/RustAudio/coreaudio-rs/issues/12). Feel free to make any fixes you require (pretty sure you have merge access to all of rustaudio) :)

**Comment by yupferris** [comment]
I've been working on it, yeah, but I ended up in a bit of a rabbit hole with other things that need to be fixed to support it properly. The idea though is to provide basically the same interface in the callback as cpal's `UnknownTypeBuffer`, and when that's there many issues (including this one) should be fixed and the plumbing in this lib should be much simpler.

**Comment by yupferris** [comment]
Feel free to also have a go at it as well though :)

**Comment by emoon** [comment]
Has there been any progress on this?

**Comment by yupferris** [comment]
@emoon: have a look at https://github.com/RustAudio/coreaudio-rs/issues/12; this issue should be trivial to fix once that issue is resolved.

**Comment by emoon** [comment]
@yupferris cool :) thanks for the info.

**Comment by yupferris** [comment]
@mitchmindtree was closing this issue intentional? It looks like merging that last PR fixed it automatically, but my understanding is we fixed only the dependent problems in coreaudio-rs, not this package yet?

**Comment by mitchmindtree** [comment]
Oh it was not intentional, my bad!

**Comment by yupferris** [comment]
Gotcha, can we re-open this then? Or, I suppose a more general "OS X Support" ticket is in order at this point.

**Comment by HybridEidolon** [comment]
This was fixed a long time ago and the example it mentions was removed, so I am closing now.
