### ISSUE TITLE
Remove the conversion system

### ISSUE THREAD

**Issue by tomaka** [tomaka/cpal#56]
After some quick conversation on IRC, it would be a good idea to move the samples conversion system out of cpal (in another library, or just ditch it) so that the only thing that cpal handles is managing the various platform-specific APIs.

Feel free to give some feedback about this.

**Comment by mceier** [comment]
I think it's good idea to move it to another library - it would give opportunity to alleviate some runtime costs, by doing offline resampling, and it also could be reused in other projects.
