### ISSUE TITLE
Consider not enumerating endpoint formats, and expose an API to set desired parameters instead?

### ISSUE THREAD

**Issue by yupferris** [tomaka/cpal#89]
Today I spent some time trying to consume this library from my [emu project](https://github.com/emu-rs/emu), a cross-platform set of libraries for writing emulators in Rust. Currently the audio stuff only works on OSX, as it depends on coreaudio-rs. The goal today was to add Windows and Linux support in one go by incorporating this library, as I'm much more in favor of wrapping a full-Rust library like this than a C library with Rust bindings, like portaudio. This would allow projects like my [SNES audio unit emulator](https://github.com/emu-rs/snes-apu) to be cross-platform, which would be quite rad :)

However, one roadblock I ran into fairly early on was that all of the supported formats for the endpoints enumerated by the WASAPI implementation were either 8000hz, 44100hz, or 48000hz. Since I need an endpoint that can support 32000hz, this wouldn't quite do. So I started digging around to see if I could find any existing audio resampling libraries in Rust, but to no avail.

However, I stumbled upon [this discussion on reddit](https://www.reddit.com/r/rust/comments/3m21pc/the_cpal_and_rodio_libraries_audio_playback/), and in particular, this quote:

> The Windows API is more restrictive, so I designed cpal to return the list of supported formats one by one. Hardwares usually support a limited number of rates, channels and datatypes, so I thought that this would be a good design.

It's mentioned that the reason this library is enumerating endpoints at all was basically because of the WASAPI abstraction, which is limited to a few very specific audio formats when used in shared mode. This raises a couple questions for me, such as, why was shared mode used in the first place? Is this because it could potentially be more performant? Could DirectSound have been used instead?

It's also noted that the current scheme also breaks down a bit with ALSA, which can have endpoints that support resampling internally, so they report a very large number of supported formats.

Additionally, had the Windows implementation used DirectSound instead of WASAPI, a similar case to ALSA would've occurred; DirectSound also supports resampling internally, which means the number of supported formats for an endpoint would also potentially be quite large. I believe using WASAPI's exclusive mode would have also exhibited this issue with the current design. And while the Core Audio parts of this library for OSX are in sort of an un-maintained state, the same would certainly hold true for that API as well.

While I agree with the logic that the hardware itself might support a select few sample rates, it appears the OS API's are much less restrictive, and I think we should consider redesigning this API to reflect that.

Back to my particular case; it might not seem too bad implementing a resampler for my project, or even writing my own OS API abstractions to give me the flexibility I need, which includes changing sample rates etc on the fly (another thing the OS API's tend to support), but I imagine many other projects that want to consume this library will run into the same issue. Perhaps this means someone should rather be working on a good audio resampling library for Rust, but I see a shorter path to solve more problems by letting the underlying OS API's handle this instead, as they already can (and can be quite robust and reliable).

I'm not entirely sure how the API would look given such a fundamental change, but I'd like to try to open up the discussion at least and see what you think before I run off and _try_ it and make a PR that may not have been welcome in the first place :)

**Comment by tomaka** [comment]
> While I agree with the logic that the hardware itself might support a select few sample rates, it appears the OS API's are much less restrictive, and I think we should consider redesigning this API to reflect that.

The idea behind this library is to offer the lowest possible common denominator between all platforms. All platforms does not mean only Windows, Linux and OSX.

The idea was to make it possible to extend to any other platform, even things like "bare metal". This is also why the API works with the writable buffers system.

> because of the WASAPI abstraction, which is limited to a few very specific audio formats when used in shared mode.

> I believe using WASAPI's exclusive mode would have also exhibited this issue with the current design.

I admit that I never tried exclude mode, but I was under the impression that only one application could use exclusive mode at a time. You don't want your application to return an error because there's already another application running that is potentially outputting sound.

Exclusive mode would give access to more formats, but not many more.

> So I started digging around to see if I could find any existing audio resampling libraries in Rust, but to no avail.

> but I imagine many other projects that want to consume this library will run into the same issue. Perhaps this means someone should rather be working on a good audio resampling library for Rust, but I see a shorter path to solve more problems by letting the underlying OS API's handle this instead, as they already can (and can be quite robust and reliable).

You should check out [rodio](https://github.com/tomaka/rodio).

**Comment by tomaka** [comment]
However I agree that the formats enumeration API is crappy.

We need something a bit more generic that doesn't assume that only a limited number of formats is supported.

But cpal will never magically guarantee that a specific format is supported everywhere.

**Comment by yupferris** [comment]
> The idea behind this library is to offer the lowest possible common denominator between all platforms. All platforms does not mean only Windows, Linux and OSX.

> The idea was to make it possible to extend to any other platform, even things like "bare metal". This is also why the API works with the writable buffers system.

Absolutely; don't get me wrong, I think this is the best lib out there in the Rust community so far for this type of thing, which is why I want to contribute in the first place :)

> I admit that I never tried exclude mode, but I was under the impression that only one application could use exclusive mode at a time. You don't want your application to return an error because there's already another application running that is potentially outputting sound.

> Exclusive mode would give access to more formats, but not many more.

I followed up on this a bit, and you're correct; exclusive mode means what it says on the tin - the application has exclusive access to the underlying audio hardware, which is a problem. We might want to look at DirectSound instead, as it's a bit more flexible in this regard, even though that may be a bit of work. I wouldn't mind looking into that, though, and that's sortof a separate issue I think.

> You should check out rodio.

rodio looks great! And it might be able to solve my original problem for sure. I'll have to give that a shot.

> However I agree that the formats enumeration API is crappy.

> We need something a bit more generic that doesn't assume that only a limited number of formats is supported.

I would suggest exposing an API similar to what Core Audio etc expose, where you can query the current audio format for an endpoint, and attempt to set it to something else, but be prepared that it may fail because the format isn't supported. I don't think it has to be more complicated than that, actually.

> But cpal will never guarantee that a specific format is supported everywhere.

Yeah, I don't think any library like this can, unless it supports its own resampling internally, which I think is definitely the _wrong_ thing to do. I think a library at this level should be concerned with exposing the features available in the supported platforms, and not try to do any more magic than that. On that note, I really like _where_ you've drawn that line between this lib and rodio, for instance. :+1:

**Comment by tomaka** [comment]
> I would suggest exposing an API similar to what Core Audio etc expose, where you can query the current audio format for an endpoint, and attempt to set it to something else, but be prepared that it may fail because the format isn't supported. I don't think it has to be more complicated than that, actually.

That's already the case!

Enumerating the list of formats only gives you the list of formats that is guaranteed to be supported. `Voice::new` lets you specify any audio format, even if they are not part of the list.

**Comment by yupferris** [comment]
> That's already the case!

Indeed it is, sorry, was thinking out loud and not so critically with that "suggestion" :)

**Comment by mitchmindtree** [comment]
Awesome to see you joining in on CPAL @yupferris :)

**Comment by yupferris** [comment]
Thanks @mitchmindtree ! I'd love to see all of these rust audio libs playing nicely together, and we're actually pretty close I think. I wanna help out with ironing out all the kinks :)

**Comment by yupferris** [comment]
Invalid issue; sorry I hadn't closed this sooner :)
